bitrise-io/bitrise

bitrise/dependencies.go

The `-p` shorthand argument to xcode-select was added in OS X 10.9; the long-form argument, `-print-path`, works in older versions of OS X.
See the discussion in Homebrew/homebrew#42862; bitrise fails on launch on 10.8 and older without this, as it thinks that Xcode/CLT aren't installed.

Dependencies: fix xcode-select argument

---

_step_template/bitrise.yml

generic format update, using `change-workdir` instead of a custom script, and added a `share-this-step` workflow for quick & easy step sharing

step template revision

---

bitrise/dependencies.go

not the right `error` was returned in "Failed to install plugin, error"
and a bit of log format revision, for better progress indicators

setup / dependency install : error passing fix

---

bitrise/print.go
cli/run.go

and the previous "running workflow", which was printed for every "before" and "after" workflow, was changed to "switching to workflow"

bitrise run now prints the workflow it was started with

---

cli/run.go

no need to print the timestamp for every line when we just list the available workflow
additionally, `printAboutUtilityWorkflows` removed as it was used only in one place, where the error line can be printed directly, otherwise the lines were the same as in `aboutUtilityWorkflows`

don't print timestamp for workflow list

---

_docs/step-development-guideline.md

To avoid potential issues like https://github.com/bitrise-io/bitrise-steplib/pull/965#issuecomment-297743757 or https://github.com/bitrise-io/bitrise-steplib/pull/356

Added version naming convention advice to step development guideline

---

cli/tools.go

without this bitrise tools ( envman, stepman ) when invoked through the CLI - e.g. `bitrise envman run ...` - will
not get an interactive input. Meaning: if you run e.g. Bash through envman, bash will exit if there are no parameters specified
and stdin is not interactive.
Example: `bitrise envman run bash`
If stdin is passed through / passed to the tool command (envman run in this case) then
youll get into an interactive bash shell this way, the same if youd run `envman run bash`.
But if you dont pass through Stdin to envman then bash will simply exit right away,
as theres no parameter for it (nothing to do) and no stdin either so it cant
ask for parameters.
This PR fixes this issue and makes `bitrise envman` and `bitrise stepman`
to behave the same as `envman ...` and `stepman ...` …

set Stdin for bitrise tools commands

---

_examples/tutorials/inputs-outputs-envs/.bitrise.secrets.yml

The example, as is, results in an error when used
`Failed to create inventory, error: Invalid inventory format: more than 2 keys specified: [BITRISE_SECRET_TEST1 is_expand opts]`

Update syntax of secrets example

---

cli/run_util.go

From this:
```
ERRO[16:35:58] Step (local step) failed, error: yaml: unmarshal errors:
line 2: cannot unmarshal !!map into string
```
to this:
```
ERRO[16:36:29] Step (local step) failed: failed to parse step definition ($HOME/Develop/go/src/github.com/bitrise-steplib/steps-xcode-test/step.yml): yaml: unmarshal errors:
line 2: cannot unmarshal !!map into string
```

fix step yml parsing error log

---

toolkits/golang.go

Updated based on the requirement of errcheck: https://github.com/kisielk/errcheck/blob/e14f8d59a22d460d56c5ee92507cd94c78fbf274/README.md#cgo
Build slug that proves it is working with go 1.11: 0f3178099c8258dd
Build slug that proves it is not working with go version less than 1.11: 068a46286691918c

Update minimum required Go version for Golang toolkit

---

bitrise/print.go
bitrise/print_test.go
bitrise/updates.go
vendor/github.com/bitrise-io/stepman/cli/activate.go
vendor/github.com/bitrise-io/stepman/cli/commands.go
vendor/github.com/bitrise-io/stepman/cli/flags.go
vendor/github.com/bitrise-io/stepman/cli/step_info.go
vendor/github.com/bitrise-io/stepman/models/models.go
vendor/github.com/bitrise-io/stepman/models/models_methods.go
vendor/github.com/bitrise-io/stepman/models/version_constraint.go

- isUpdateAvailable was moved to a separate file and heavily refactored, because of the new requirements
- update info printing got refactored in a separate function
- **monkey patched SetInfoModel in vendor to make CI pass, until dependency is updated**

Tool 1347 log new step version info

---

bitrise/print.go
bitrise/print_test.go
bitrise/updates.go
vendor/github.com/bitrise-io/stepman/cli/activate.go
vendor/github.com/bitrise-io/stepman/cli/commands.go
vendor/github.com/bitrise-io/stepman/cli/flags.go
vendor/github.com/bitrise-io/stepman/cli/step_info.go
vendor/github.com/bitrise-io/stepman/models/models.go
vendor/github.com/bitrise-io/stepman/models/models_methods.go
vendor/github.com/bitrise-io/stepman/models/version_constraint.go

* refactor: extract function
* print resolved version when applicable
* refactor: simplify conditionals
* refactor: simplify conditional
* test cases: version row for major and minor lock
* build correct version info row string
* refactor: remove useless code
* print dotted changelog URL
* refactor: put major and minor test case together
* test case: url cropping
* empty line in box under version info
* dont show update info if latest version fits
lock
* remove development related temp code
* remove unrelated logic from tests
* improve test case name
* refactor: simplify string production
* test case for 1.x and 1.x.x format
* refactor: extract update handling to separate file
* refactor: consolidate update check flow
* handle semver parse error
* remove testing code
* refactor: make …

Tool 1347 log new step version info (#692)

---

bitrise.yml
bitrise/util_test.go

`$ go help testflag`
```
-parallel n
Allow parallel execution of test functions that call t.Parallel.
The value of this flag is the maximum number of tests to run
simultaneously; by default, it is set to the value of GOMAXPROCS.
Note that -parallel only applies within a single test binary.
The 'go test' command may run tests for different packages
in parallel as well, according to the setting of the -p flag
(see 'go help build').
```
`$ go help build`
```
-p n
the number of programs, such as build commands or
test binaries, that can be run in parallel.
The default is the number of CPUs available.
```
Created a test case run timeline graph with the default settings:
Also created a graph with `-p 1`:
So it is clearly visible that packages are running in parallel and also that it can be …

TOOL-1907 fix flaky CI test case

---

cli/run_util.go
cli/run_util_test.go

Code should check if it is possible to cast to string and return the default representation of the value for non nil values.

[TOOL-2041] Access Environment item values with GetKeyValuePair instead of [] operator

---

_tests/integration/log_filter_test.go
_tests/integration/log_filter_test_bitrise.yml
tools/filterwriter/filterwriter.go
tools/filterwriter/filterwriter_test.go

Related to this: https://bitrise.atlassian.net/browse/PLAT-889
This code ensures that secrets stored in env vars are obscured correctly even if they are printed with escaped newlines (literal `\n`).

[PLAT-892] Obscuring secrets with escaped newlines in output

---

cli/update.go

Fixing failing CI due to the change in brew.
> brew list failed, Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.

Append `--formula` arugment to "brew list"

---

cli/run_test.go
cli/run_util.go
models/models.go
plugins/events.go
plugins/model_methods_test.go
plugins/models.go
plugins/paths.go
plugins/run.go

- Requires _MINOR_ [version update](https://semver.org/)
Extend Bitrise CLI with trigger capability so plugins are capable of listening to multiple Triggers
Resolves: [STEP-377](https://bitrise.atlassian.net/browse/STEP-377)
- Extended both `Plugin` and `PluginRoute` with `TriggerEvents` property to enable adding multiple events to a plugin.
- Introduce `WillStartRun` trigger which is called before the build is started.
- Introduce `BuildRunStartModel`
- Added `TestPluginTriggered` test in `run_test.go` to cover plugins being called.
- Created a `ForceInitPaths` function in  `plugins` package to mock the plugins installed.

Introduce triggers for plugins.

---

configs/paths.go
configs/paths_test.go

Having a temporary directory created to be included in the cache push
step has no value as it changes on each workflow run. Anything put there
would be dropped by the next iteration and the user would not be able
to access the content easily anyway.
[STEP-447]
[STEP-447]: https://bitrise.atlassian.net/browse/STEP-447

Remove temporary directory generation for `BITRISE_CACHE_DIR`

---

_docs/step-development-guideline.md

* Many steps run as a wrapper around specific command-line tools, such as `xcodebuild`.
* Although steps try to provide inputs for managing most arguments of those tools for ease of use, this is not always the case.
* Therefore, providing additional command-line arguments should always be possible via a dedicated step input (e.g. via `xcodebuild_options` in case of Xcode Archive).
* Steps should follow this as a best practice.
* **Added a section about additional command-line arguments to Step Development Guidelines.**

Add section about additional command-line arguments to Step Development Guidelines

---

bitrise.yml
toolkits/swift.go
toolkits/toolkit.go
vendor/github.com/bitrise-io/stepman/models/models.go

This is a proof of concept PR that demonstrates the CLI executing steps written in Swift. 
The RFC that describes this effort is available [here](https://bitrise.atlassian.net/wiki/spaces/ENGI/pages/2402910342/RFC).
The CLI has two ways to run swift code:
1) Executing the source code directly by locating the package (local/remote), compiling the code, then running the code. This is useful for testing and local dev. 
2) Executing a precompiled binary. This is more efficient and will be useful for released steps. 
Once we're aligned on the approach, there will be efforts to formalize this in the bitrise yaml spec, as well as PRs against the vendor deps and tests.

Proof of Concept: First class support for steps written in Swift.

---

analytics/state_checker.go
analytics/tracker.go
go.mod
go.sum
vendor/github.com/bitrise-io/go-utils/v2/analytics/client.go
vendor/github.com/bitrise-io/go-utils/v2/analytics/sync_track.go
vendor/github.com/bitrise-io/go-utils/v2/analytics/track.go
vendor/modules.txt

The *BITRISE_ANALYTICS_V2_ASYNC* env var can be set to `false` to use analytics that blocks when called.

Add option to serialize analytics for debugging

---

_tests/integration/helper.go
_tests/integration/timeout_no_output_test.go
_tests/integration/timeout_test.go
cli/run.go
exitcode/exitcode.go
models/models_methods.go

Set different exit codes based if there were Steps which were aborted:
- Step aborted by custom timeout set in the bitrise.yml: 11
- Step aborted by no output timeout: 12
- Any other failure: 1
These will be used to display a relevant message on the frontend.
Resolves: https://bitrise.atlassian.net/browse/BE-198

[BE-198] Set different exit status for aborted builds

---

_tests/integration/timeout_no_output_test.go
_tests/integration/timeout_test.go
analytics/tracker.go
analytics/tracker_test.go
bitrise/print.go
bitrise/print_test.go
cli/run_util.go
exitcode/exitcode.go
models/models.go
models/models_methods.go
tools/hangdetector/hang_detector.go
tools/hangdetector/hang_detector_test.go

- Forward timeouts from Steps and wrapped bitrise processes.
- Added heartbeat message, this helps avoiding the case where a wrapper bitrise process aborts earlier then the wrapped bitirse process (if both use the same timeout).
- Updated exit codes to less common numbers to avoid confusion with exit codes from shell scripts.
Resolves: https://bitrise.atlassian.net/browse/BE-198

[BE-198] Forward wrapped bitrise status

---

cli/run_util.go
cli/step_info.go
cli/step_list.go
go.mod
go.sum
tools/tools.go
tools/tools_test.go
vendor/github.com/bitrise-io/go-utils/versions/versions.go
vendor/github.com/bitrise-io/stepman/cli/activate.go
vendor/github.com/bitrise-io/stepman/cli/audit.go
vendor/github.com/bitrise-io/stepman/cli/cli.go
vendor/github.com/bitrise-io/stepman/cli/collections.go
vendor/github.com/bitrise-io/stepman/cli/delete_steplib.go
vendor/github.com/bitrise-io/stepman/cli/download.go
vendor/github.com/bitrise-io/stepman/cli/export.go
vendor/github.com/bitrise-io/stepman/cli/setup.go
vendor/github.com/bitrise-io/stepman/cli/share_audit.go
vendor/github.com/bitrise-io/stepman/cli/share_create.go
vendor/github.com/bitrise-io/stepman/cli/share_finish.go
vendor/github.com/bitrise-io/stepman/cli/share_start.go
vendor/github.com/bitrise-io/stepman/cli/step_info.go
vendor/github.com/bitrise-io/stepman/cli/step_list.go
vendor/github.com/bitrise-io/stepman/cli/update.go
vendor/github.com/bitrise-io/stepman/cli/version.go
vendor/github.com/bitrise-io/stepman/models/version_constraint.go
vendor/github.com/bitrise-io/stepman/stepman/library.go
vendor/github.com/bitrise-io/stepman/stepman/paths.go
vendor/github.com/bitrise-io/stepman/stepman/util.go
vendor/modules.txt

This PR makes Bitrise CLI use stepman functionalities through exported functions rather than through envman binary calls.
- Update `tools.Stepman<Function>s` to use stepman exported functions.
- stepman `step-list` and `share` functions were not migrated because they are not used by the workflow run command

Stepman functions

---

cli/run.go
models/workflow_run_plan.go

This PR updates `bitrise run` structured logs by removing the redundant `target_workflow_id` from the workflow run plan model.
Earlier the build log highlighted the target workflow when printing the list of the workflows to be executed, but it isn't anymore.
- Remove `target_workflow_id` from WorkflowRunPlan

Remove target_workflow_id from workflow run plan

---

log/log.go
log/log_functions.go
log/logger.go

Use the version from the `models.WorkflowRunPlan` when printing the Bitrise CLI header.

Add version as input to Bitrise CLI header

---

version/build.go

Currently, Bitrise CLI has a template version hardcoded, which gets overridden when it is built on CI.
When Bitrise CLI is built in any other way, it will print the template version.
When running an experiment on a new Bitrise CLI version, the CLI gets updated with `go install github.com/bitrise-io/bitrise@<revision>`. 
When using a version tag as revision printing the template version (`1.99.0-development`) is unexpected.
This PR sets the version number to the next version to be released (2.0.1).
- update the version number to 2.0.1

Update version to 2.0.1

---

log/logwriter/writer.go
log/logwriter/writer_test.go

When structured JSON logging is used, don't log empty messages to reduce the complexity and improve performance by not sending an empty json structure to the build-log-service
structured log writer's write method short circuits empty log messages + test coverage to make sure formatting is preserved

fix: don't log empty messages

---

version/build.go

This PR bumps the Bitrise CLI version to 2.0.2.
- version bump

Bump version to 2.0.2

---

version/build.go

This PR updates Bitrise CLI version to 2.1.0.

Update version number to 2.1.0

---

bitrise/setup.go

This PR updates the default plugin versions, to make the [latest analytics plugin](https://github.com/bitrise-io/bitrise-plugins-analytics/releases/tag/0.13.0) the default with the updated analytics service base URL.
New default plugin versions:
- init plugin: 1.9.1 -> [1.10.0](https://github.com/bitrise-io/bitrise-plugins-init/releases/tag/1.10.0)
- analytics plugin: 0.12.7 -> [0.13.0](https://github.com/bitrise-io/bitrise-plugins-analytics/releases/tag/0.13.0)

Update default plugin versions

---

version/build.go

This PR bumps Bitrise CLI version to 2.2.0, for releasing:
- https://github.com/bitrise-io/bitrise/pull/838
- https://github.com/bitrise-io/bitrise/pull/839
- https://github.com/bitrise-io/bitrise/pull/840
- version: 2.1.0 -> 2.2.0

Bump version to 2.2.0

---

bitrise/dependencies.go
cli/json_output.go
cli/plugin_info.go
cli/plugin_list.go
cli/validate.go
cli/workflow_list.go
utils/utils.go

This PR fixes a bug with structured logging: before Bitrise CLI installs an apt-get package, an apt-get update command is executed, which was writing to the os.Stdout directly. This resulted in a raw log, even if structured logging was enabled (`--output-format json`)
- Hide the apt-get update command output as long as the command succeeds, return the output as part of the returned error otherwise
- Stop CheckProgramInstalledPath to print to os.Stderr
- Typo fix: longer -> logger
I was searching for `os.Stdout` and `os.Stderr` in the codebase to find all the occurrences where we write directly to the standard output.

Command logs

---

cli/build_run_result_collector.go
cli/run.go
cli/run_config.go
cli/run_test.go
cli/run_util.go
cli/trigger.go
configs/configs.go
models/models.go
models/models_test.go

This PR fixes a crash in the Bitrise CLI, which happens when no-output-timeout is defined through secrets (and NOT as a step property) and a step meets the timeout.
The bug can be reproduced by using this workflow:
```
no_output_timeout_test:
steps:
- script:
inputs:
- content: |-
sleep 10
```
and specifying 5s timeout as a secret (`.bitrise.secrets.yml`):
```
envs:
- BITRISE_NO_OUTPUT_TIMEOUT: 5
```
`bitrise run no_output_timeout_test` will panic:
```
[15:29:13] No output received for a while. Bitrise CLI is still active.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1027ca36c]
goroutine 1 [running]: …
```

Fix for the no output timeout related crash

---

toolkits/command_runner.go
toolkits/golang.go
toolkits/golang_test.go

This PR stops Go toolkit printing directly to the os.Stdout, which messes up structured logging.
- Set the gows command's std `out`, `err`, and `in` to nil and execute with `runForOutput`
- Remove `run` from the `commandRunner`, because it allows running commands, which might directly write to the stdout.
As an alternative solution, I tried to utilize the v2 command package because the [Factory.Create](https://github.com/bitrise-io/go-utils/blob/master/command/command.go#L42) method enforces a code where you allow the client to specify the command std interface.
I tried to implement a similar solution that we have in the ruby package for gows: https://github.com/bitrise-io/gows/commit/dbd258a214bc70fe36b14a6dea271351537b80d4
The …

stop gows command printing to the stdout directly

---

_tests/integration/global_flag_test.go
bitrise/template_utils_test.go
cli/run_test.go
cli/run_util_test.go
configs/configs_test.go
configs/paths_test.go
models/models_methods_test.go
toolkits/golang_test.go

This PR replaces `os.Setenv` with `t.Setenv` in `*_test.go` files.
- Replaces `os.Setenv` with `t.Setenv`
- Refactor several test functions to table-driven tests so that `t.Setenv` performs the cleanup after each subtest.
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```

test: use `t.Setenv` to set env vars in tests

---

cli/step_activator.go
go.mod
go.sum
vendor/github.com/bitrise-io/go-utils/command/file.go
vendor/modules.txt

Requires a */PATCH* [version update](https://semver.org/)
This PR solves the issue of rsync directly writing to the stdout, when the CLI [activates a local Step](https://github.com/bitrise-io/bitrise/blob/master/cli/step_activator.go#L36-L53) and the provided directory path is invalid.
When structured logging is enabled, the rsync log messes up the structured logging.
- Update go-utils/command package to pull the [rsync fix](https://github.com/bitrise-io/go-utils/pull/178)
- Validate if the provided local step directory and step.yml exist

Update go-utils/command package

---

version/build.go

This PR bumps the CLI version from 2.2.1 to 2.2.2 before releasing the changes:
- https://github.com/bitrise-io/bitrise/pull/846
- https://github.com/bitrise-io/bitrise/pull/847
- https://github.com/bitrise-io/bitrise/pull/849
- Bump version number from 2.2.1 to 2.2.2

Bump version to 2.2.2

---

cli/run_util.go

The validation command prints raw log statements when the `-format json` parameter is used. 
This blocks https://github.com/bitrise-io/bitrise/pull/844
Three unnecessary log lines are removed. They are not needed because the `CreateBitriseConfigFromCLIParams` function was returning with the same information as an error as what was printed as a warning before the return statement. The warning level was already incorrect because an error is returned and also following all of the code paths using `CreateBitriseConfigFromCLIParams` revealed that the returned error is an execution stopper and the cli was killed. 
So by removing them we can quickly fix the raw logs appearing in the output without losing anything important.

Remove log lines

---

_tests/integration/log_format_test.go
_tests/integration/log_format_test_bitrise.yml
cli/run_util.go

With the structured logging we were using the cli debug flag to show or hide the step level debug logs. This is not correct because it can happen that the user want to only see a specific step's debug logs. This change will make the cli always print put the debug logs if they are coming from a step.
The steps have their own input field for indicating the debug level. That means that the steps are responsible for handling their own debug logs. So the cli can safely always print out the debug logs received from the step.

[CI-857] Handle step level debug logs

---

log/logwriter/writer.go
log/logwriter/writer_test.go

When LogWriter receives a message that seems to be a message with log-level (the message starts with one of the know ANSI color codes), but the message has a color reset character in the middle, it was not handled properly and LogWriter was waiting for the end of the log-leveled message.
If the executed command was waiting for a user input after such a message, the CLI ended up not writing anything to the output.
This can be reproduced by running the step plugin's create command (`bitrise :step create`) using this CLI revision: b8b3e796f118359e91faad5c984b870946249634.
This PR fixes this issue, by not treating a message with log-level if the message contains a color reset sequence in the middle of the content.
- Update …

Handle color reset in the middle of the message

---

models/models.go

[[CI-1429](https://bitrise.atlassian.net/browse/CI-1429)] The validate subcommand does not validate the `run_if` field on stages.
* Added the missing property to the stage model
I think this is not needed for a couple reasons:
1. The property is not currently added to the models in the CLI -- this tells me it's fine for it to be missing from the CLI models
1. Although we can add it for the sake of completeness
2. The CLI is not the one that will process this condition, that happens at whatever level is executing the stage (DEN?)
3. We can’t really do pre-runtime validation on this because the condition may contain env vars
4. If we follow the example of the existing step model's `run_if` then I noticed:
1. It is a string type so its …

Added RunIf field on stage workflow for validation

---

_tests/integration/gomodmigrate.yml
_tests/integration/version_test.go
cli/run.go
version/init.go

The cli can installed two ways in our stack:
- Preinstalled
- Installed by the den agent with `go install`
The problem we had is that we currently cannot differentiate the two and this caused some problems during the last cli incident. 
This PR will change the cli's behaviour to print extra information into the build log if it was installed by `go install`. This extra information is the git hash which was used to install it. If the cli was preinstalled from a binary release then it will print no extra information.
Tested it with our system:
The cli reads the build information and if it exists (it will for `go install` based installations) then it will populate the `Commit` variable from there.

[CI-1546] Detect alternative installation

---

version/build.go

This PR bumps the CLI version to 2.2.7.
The latest release is [2.2.6](https://github.com/bitrise-io/bitrise/releases/tag/2.2.6), but for that release updating the version number in the code was forgotten, that's why this PR bumps from 2.2.5 -> 2.2.7.

Update version number

---

_tests/integration/log_format_test.go
cli/run_util.go
cli/step_activator.go
plugins/run.go
stepoutput/stepoutputwriter_test.go
tools/tools.go

The goal of this PR is to leave less room for engineers to accidentally break the secret redaction on the step run logs.
One change is discarding the usage of (and removing) `tools.EnvmanRun`, as the rest of its features are only used when running a step, but at the same time the `tools.EnvmanRun` seemed to be a generic function, which is open for many configurations.
Another change is testing if the root writer of the `stepoutput.Writer` is a secret redactor when secrets are provided.
Resolves: https://bitrise.atlassian.net/browse/CI-1102
- Remove EnvmanRun and move it's logic to `WorkflowRunner.executeStep`
- Use go-utils command for running plugins
- Move `activateStepLibStep` from run_utils.go to step_activator.go (as it is used …

Step run func

---

_lessons/lesson1_steps/README.md
models/models.go

BIVS-1969
More human readable description of pipelines and workflow to enable adding more visibility to them, by adding a title, summary and description field to pipeline elements. Registration of these fields is required so that the WFE workflows tab save button doesn't remove them from an existing bitrise.yml.
Adds `title`, `summary` and `description` to the [PipelineModel](https://github.com/bitrise-io/bitrise/blob/d2d4706931314efcc7cda16bf9b7a9ca04a0e90e/models/models.go#L21) and [StageModel](https://github.com/bitrise-io/bitrise/blob/d2d4706931314efcc7cda16bf9b7a9ca04a0e90e/models/models.go#L29)
When editing the bitrise.yml in the visual WFE, the save button on the workflows tab removes all unknown fields 😞

feat: add title, summary and description to the pipeline model

---

bitrise/setup.go

This PR updates the workflow editor plugin version to the latest version ([1.3.234](https://github.com/bitrise-io/bitrise-workflow-editor/releases/tag/1.3.234)).
This workflow editor version [supports Pipeline and Stage title, summary, and description](https://github.com/bitrise-io/bitrise-workflow-editor/pull/793).
Resolves: https://bitrise.atlassian.net/browse/BIVS-1995
- Update workflow editor plugin version to 1.3.234

Update default workflow editor plugin version

---

_tests/integration/version_test.go
models/models.go
version/build.go

bitrise.yml data model got new fields in this PR: https://github.com/bitrise-io/bitrise/pull/876.
This PR bumps the bitrise.yml data model format version to `13` and Bitrise CLI version number to `2.3.0`.
Resolves: https://bitrise.atlassian.net/browse/BIVS-1995
- bump `FormatVersion` to 13
- bump `VERSION` to 2.3.0

Bump models format version to 13 and version number to 2.3.0

---

analytics/tracker.go

This PR adds `app_slug` property to the `workflow_started` event. This is needed because project scanner builds (during the add new app flow) don't have the `build_slug` property, so they can't be connected to Bitrise Apps (which helps better understand project scanner failures).
https://bitrise.atlassian.net/browse/BIVS-2069
- Add `app_slug` property to the `workflow_started` event

Add app_slug property to the workflow_started event

---

_tests/integration/secret_keys_sharing_test.go
_tests/integration/secret_keys_sharing_test_bitrise.yml
_tests/integration/secret_keys_sharing_test_secrets.yml
cli/run_util.go
go.mod
go.sum
tools/tools.go
vendor/github.com/bitrise-io/go-steputils/v2/secretkeys/secretkeys.go
vendor/modules.txt

The deploy to bitrise io and the share pipeline env var steps will need to know about the available secrets so they can provide extra functionality. This PR introduces the necessary changes on the CLI side.
The core of the logic is in the go-utils lib because it will be shared between 3 items. 
Other than that the CLI only used the secret values for redaction but now it also needs the keys so I modified a few functions to also accept the keys too.

[CI-1803] Secret env sharing

---

bitrise/template_util.go
bitrise/template_utils_test.go

This PR extends the functionality in condition template evaluation. `envcontain` checks if an environment variable contains a  substring or not.

Add envcontain to template string evaluation

---

_tests/brew_publish.yml
_tests/integration/validate_test.go
bitrise/setup.go
cli/commands.go
cli/export.go
cli/flags.go
cli/normalize.go
cli/run.go
cli/step_info.go
cli/step_list.go
cli/trigger.go
cli/trigger_check.go
cli/validate.go
cli/workflow_list.go

According to git blame, this has been deprecated 8 years ago 😵‍💫 
Clean up the `--path` flag from the various subcommands.

Remove long-deprecated --path flag

---

version/build.go

This PR updates Bitrise CLi version from 2.5.0 to 2.6.0, before releasing these changes:
- https://github.com/bitrise-io/bitrise/pull/888
- https://github.com/bitrise-io/bitrise/pull/891
- https://github.com/bitrise-io/bitrise/pull/892
- https://github.com/bitrise-io/bitrise/pull/894
- https://github.com/bitrise-io/bitrise/pull/896
- https://github.com/bitrise-io/bitrise/pull/897
- update version number

Update version to 2.6.0

---

bitrise/dependencies.go
go.mod
go.sum
plugins/install.go
progress/progress.go
toolkits/golang.go
vendor/github.com/bitrise-io/go-utils/command/command.go
vendor/github.com/bitrise-io/go-utils/log/internal_logger.go
vendor/github.com/bitrise-io/go-utils/progress/spinner.go
vendor/github.com/bitrise-io/go-utils/progress/wrapper.go
vendor/modules.txt

This PR updates the go-utils package to have this code change in the CLI:
https://github.com/bitrise-io/go-utils/pull/191
Other than that I have created a new wrapper for the progress indicator which will always inject our custom logger as the output.
This example output was taken with these changes:
```
{"timestamp":"2023-12-06T13:17:38.229375Z","type":"log","producer":"bitrise_cli","level":"normal","message":"Installing ⣾"}
{"timestamp":"2023-12-06T13:17:38.329614Z","type":"log","producer":"bitrise_cli","level":"normal","message":"\u0008"}
{"timestamp":"2023-12-06T13:17:38.329664Z","type":"log","producer":"bitrise_cli","level":"normal","message":"\u0008"}
{"timestamp":"2023-12-06T13:17:38.32967Z","type":"log","producer":"bitrise_cl …
```

[CI-2304] Progress indictor output change

---

toolversions/toolversions.go
toolversions/toolversions_test.go
vendor/github.com/bitrise-io/go-utils/v2/command/command.go
vendor/github.com/bitrise-io/go-utils/v2/command/errorcollector.go
vendor/modules.txt

Telemetry for how tool version managers are used, what are the active versions during the build, etc.
- Define an interface for tool version reporting
- Implement this reporting logic for ASDF, the version manager that we use on the stacks. We could extend or replace this impl if needed

Tool version reporting

---

analytics/state_checker.go
analytics/tracker.go
cli/run_test.go
cli/run_util.go
toolversions/toolversions.go
toolversions/toolversions_test.go

Follow up to #902 
- Send the collected tool version report as a standard telemetry event.
- Add a few more useful properties to the event
As the tool version map contains arbitrary key-value pairs and we'll add more tools under ASDF, I decided to just serialize everything as JSON. We can process the JSON at query-time easily.

Tool version telemetry

---

_tests/integration/helper.go
_tests/integration/json_params_test.go
_tests/integration/new_trigger_test.go
_tests/integration/new_trigger_test_bitrise.yml
cli/commands.go
cli/run_trigger_params.go
cli/run_trigger_params_test.go
cli/trigger.go
cli/trigger_check.go
models/models_methods_test.go
models/trigger_map.go
models/trigger_map_item.go
models/trigger_map_item_test.go
models/trigger_map_test.go

This PR introduces support for controlling whether a draft Pull Request should trigger a workflow run or not.
To disable the draft PR trigger set `draft_pull_request_enabled: false` on a Pull Request trigger item:
```
trigger_map:
- pull_request_source_branch: feature*
pull_request_target_branch: main
draft_pull_request_enabled: false
workflow: ci
```
By default (when `draft_pull_request_enabled` is not specified) a draft PR will continue to trigger a workflow run.
- New `draft_pull_request_enabled` property introduced on the `TriggerMapItemModel`, which controls the draft PR trigger, it defaults to true
- The `trigger` and `trigger-check` commands got a new bool flag `--draft-pr`, which describes if the incoming PR is in a draft …

Control draft pr trigger

---

version/build.go

This PR updates Bitrise CLI version to 2.8.0, to prepare for releasing:
- https://github.com/bitrise-io/bitrise/pull/905
- https://github.com/bitrise-io/bitrise/pull/907
- Update version number in `version/build.go` to 2.8.0

Update version number to 2.8.0

---

_tests/integration/new_trigger_test.go
cli/commands.go
cli/run_trigger_params.go
cli/run_trigger_params_test.go
cli/trigger.go
cli/trigger_check.go
models/trigger_map.go
models/trigger_map_item.go
models/trigger_map_item_test.go
models/trigger_map_test.go

This PR fixes an issue with the previously introduced draft PR trigger control.
The previous implementation couldn't handle properly when a draft PR is converted to a ready-for-review status.
The new implementation compares PR trigger map items to a PR readiness status with three possible values: `draft`, `ready_for_review` and `converted_to_ready_for_review ` this way:
If the draft PR trigger is enabled:
- build params with `pull_request_ready_state=draft` → trigger a build
- build params with `pull_request_ready_state=ready_for_review` → trigger a build
- build params with `pull_request_ready_state=converted_to_ready_for_review` → skip build (only the ready state has changed, build was already running on this state of the code)
If …

Update draft PR control

---

version/build.go

This PR updates Bitrise CLI version to 2.9.1, to prepare for releasing:
- https://github.com/bitrise-io/bitrise/pull/912
- Update version number in `version/build.go` to 2.9.1

Bump version number to 2.9.1

---

models/models.go
models/models_methods.go
models/models_methods_test.go

The `StageModel` struct used the `WorkflowListItemModel` for its workflows which is the same model as what is used to describe the actual workflows. This is wrong for two reasons. 
One is that obviously you should not be able to define a whole workflow in the stage itself because that is not the place for it. For example, our yaml validation only allows a single `run_if` field to be defined in a stage workflow definition:
https://github.com/bitrise-io/bitrise-json-schemas/blob/2742accae7a40620f9d6d2322aa3f8679e2a3a6f/bitrise.schema.json#L400-L408
Second is that right now when the local workflow editor customers save their yaml the `run_if` field is removed from the stage workflows. They need to manually edit the yaml and add it …

[CI-2392] Use new model for stage workflow

---

bitrise/setup.go
plugins/install_test.go

Do no longer install analytics plugin in `bitrise setup`.

Setup no longer installs analytics plugin

---

_tests/integration/version_test.go
models/models.go
models/models_methods.go
models/models_methods_test.go
models/trigger_map.go
models/trigger_map_item.go
models/trigger_map_item_test.go
models/trigger_map_test.go

Resolves: https://bitrise.atlassian.net/browse/BIVS-2506
This PR updates the bitrise.yml data model to support advanced trigger map features:
New fields introduced on the Trigger Map items:
- `type`: describes whether the item responds to a Code Push (`push`), Pull Request (`pull_request`) or Tag (`tag`) webhook event. This field is required if the item type can be determined based on the item conditions:
- A Code Push Item doesn't have `push_branch` set
- A Pull Request item doesn't have `pull_request_source_branch` or `pull_request_target_branch` set
- A Tag item doesn't have `tag` set
- `enabled`: tells if the given item should be considered at trigger check. Defaults to `true`.
- For Code Push Items:
- `commit_message`
- …

Advanced trigger map

---

bitrise/setup.go
version/build.go

This PR bumps Bitrise CLI version to 2.11.0 and updates the default plugins to the current latest versions, as a preparation for releasing the [recent 'advanced trigger map' related changes](https://github.com/bitrise-io/bitrise/pull/932).

Update Bitrise CLI and default plugins' version

---

analytics/state_checker.go
analytics/tracker.go
cli/run.go
cli/run_test.go

A follow-up to #930, clean up a few leftover things.
- Print analytics message at the beginning of the build (it used to be printed by the now-removed analytics plugin)
- Clean up old env vars controlling analytics

Clean up analytics leftovers

---

models/trigger_map_item.go
models/trigger_map_item_test.go
models/trigger_map_test.go

This PR fixes an issue with trigger map validation. The validation process considered trigger map items with the same conditions, but different types as duplicates.
For example, `bitrise validate` thrown a `the 2. trigger item duplicates the 1. trigger item` error fr the following trigger map:
```
trigger_map:
- type: pull_request
changed_files: "*.md"
workflow: check
- type: push
changed_files: "*.md"
workflow: check
```
- Consider the type of the trigger item, when duplication is tested.

Fix triggr item duplicatin check

---

version/build.go

This PR bumps the Bitrise CLI version number to 2.13.1, before releasing:
- https://github.com/bitrise-io/bitrise/pull/948
- https://github.com/bitrise-io/bitrise/pull/947

bump version number to 2.13.1

---

analytics/tracker.go
cli/cli.go
cli/cli_test.go
cli/run.go
cli/run_test.go

We want to better understand how our users are using the CLI so we will be collecting what commands are executed and which flags are used. 
I have extended the existing logger with a new event. 
At the moment the run command was initialising the tracker and it was the only user of it. This was not good because we need to log the command info much earlier. So I moved the tracker initialisation where the CLI execution starts. With this there was a new problem with how to share this tracker with the run command. 
We are using the urfave cli package to parse and execute the tasks. This package has a `Context` (not the same as the Go `Context` one) struct which will trickle down to the commands. But you can only add strings to it. So the …

[CI-2937] CLI command logging

---

_tests/integration/docker_create_bitrise.yml
_tests/integration/docker_multiple_containers_bitrise.yml
_tests/integration/docker_multiple_containers_secrets.yml
_tests/integration/docker_pull_bitrise.yml
_tests/integration/docker_service_bitrise.yml
_tests/integration/docker_start_fails_bitrise.yml
_tests/integration/docker_test.Dockerfile.healthy-container
_tests/integration/docker_test.go
cli/docker/container_manager.go
cli/run.go
cli/run_util.go
models/models.go
models/models_methods.go
models/models_methods_test.go
models/workflow_run_plan.go

Containerization-related configuration is getting refactored:
1, Moving service and container configuration to new top-level entities (services and containers): https://github.com/bitrise-io/bitrise/pull/952
2, Step grouping mechanism with a new step list item (`with`)
From this:
```
workflows:
_setup:
steps:
- activate-ssh-key: { }
- git-clone: {}
test:
before_run:
- _setup
container: ruby
services:
- postgres
steps:
- script:
title: Setup DB
inputs:
- content: bundle exec rails db:setup
- script:
title: Run tests
inputs:
- content: bundle exec rspec
```
to this:
```
workflows:
test:
steps:
- activate-ssh-key@4: { }
- git-clone@8: {}
- with:
container: ruby
services:
- postgres
steps:
- script:
title: Setup DB
inputs:
- …
```

Refactor containerisation 2

---

version/build.go

This PR updates Bitrise CLI version number from 2.15.0 to 2.16.0 to release the [containerization config](https://github.com/bitrise-io/bitrise/pull/964) related changes.

Update version number to 2.16.0

---

cli/run_util.go
cli/step_activator.go

#973 
Cleaning up the refactored code paths

Clean up activator

---

go.mod
go.sum
models/models_methods.go
models/models_methods_test.go
vendor/github.com/bitrise-io/envman/models/models_methods.go
vendor/modules.txt

This PR fixes the bitrise config normalization. Normalization converts maps with interface{} keys to string-keyed maps, to make the config JSON compatible.

Fix config normalise

---

version/build.go

This PR bumps Bitrise CLI version number from 2.20.0 to 2.20.1, to release https://github.com/bitrise-io/bitrise/pull/995 .

Bump version number from 2.20.0 to 2.20.1

---

cli/cli.go
cli/cli_test.go
cli/command_analytics.go
cli/init.go
cli/merge.go
cli/plugin_delete.go
cli/plugin_info.go
cli/plugin_install.go
cli/plugin_list.go
cli/plugin_update.go
cli/preload_steps.go
cli/run.go
cli/setup.go
cli/share.go
cli/share_audit.go
cli/share_create.go
cli/share_finish.go
cli/share_start.go
cli/tools.go
cli/trigger.go
cli/trigger_check.go
cli/update.go
cli/validate.go
cli/version.go
cli/workflow_list.go

The previous command line parser was not handling all the edge cases and was logging incorrect data. For example, us and the users are calling the CLI with not a fix parameter type order. 
In this iteration I am relying on the `urfave/cli` package to get access to the parameter list. It already knows the correct parameters for a given command / subcommand so by the time the action starts we can have access to a correct parameter list.

[CI-3190] Improve parameter logging

---

bitrise/setup.go
configs/configs.go
configs/configs_test.go

It's not clear why the implicit setup is triggered in some cases, and it's enough to run a minimal setup only (see #944)

Better logs when running implicit setup; do minimal setup only

---

version/build.go

This PR bumps the version number from 2.21.0 to 2.22.0, to release:
- https://github.com/bitrise-io/bitrise/pull/1003

Bump version number to 2.22.0

---

models/models.go
models/models_test.go

There were a couple of graph pipeline validations which were not yet added to the CLI.

Add missing graph pipeline validation

---

models/models.go
models/models_methods.go
models/models_methods_test.go

This PR introduces support for configuring custom build status report names in the bitrise.yml configuration file.
By default, Bitrise uses the `ci/bitrise/<project_slug>/<event_type>` status report name (or simply `Bitrise` for legacy GitHub Checks enabled projects).
The default value can be overwritten at App level and Workflow and Pipeline level too:
```
---
format_version: '13'
app:
status_report_name: "ci/bitrise/<project_slug>/<target_id>/<event_type>"
pipelines:
pipeline:
status_report_name: "Custom status name for a pipeline"
workflows:
primary:
status_report_name: "Custom status name for a workflow"
```
The custom status name must be a maximum of 100 chars long and must match the `^[a-zA-Z0-9,./():\-_ <>[\]|]*$` regex.

Custom status report names

---

version/build.go

This PR bumps Bitrise CLI version from 2.23.0 to 2.24.0, to release:
- https://github.com/bitrise-io/bitrise/pull/1013

Bump version to 2.24.0

---

cli/run_util_pipeline_test.go
models/models_methods.go
models/models_methods_test.go

Empty pipelines are valid so the WFE can save a not fully defined pipeline.

Remove empty pipeline validation

---

bitrise.yml

This PR adds a deploy step to the run_docker_integration_tests, to report test results status.

Add missing deploy step to run_docker_integration_tests step bundle

---

bitrise.yml

This PR improves on the CI configuration:
- enables release workflow triggering by tag events
- unifies the stacks used by different workflows
- macOS -> osx-xcode-edge
- linux -> (default stacks) linux-docker-android-22.04
- except docker tests, those are on linux-docker-android-20.04
- update status report name
- Run integration tests and export results (Integration tests (Linux)) -> Run integration tests (Integration tests on Linux)
- Run integration tests and export results (Integration tests (macOS)) -> Run integration tests (Integration tests on macOS)
- Run integration tests and export results (Linux only integration tests) -> Run integration tests (Linux only integration tests)
- Run unit tests and export results (Unit tests …

Enable release workflow and unify workflow stacks

---

cli/agent.go
cli/docker/container_manager.go
cli/run_util_pipeline_test.go
log/log.go
models/models.go
models/models_methods.go

[CI-4035]
- introduce `uses` attribute for workflows in a graph pipeline
- validation should behave somewhat differently for those workflow variants
- out intention is to keep this feature experimental for now (meaning it might change in the future, e.g. the naming of field)
- but we would like to start using it internally, and we can't as the current CLI version doesn't consider workflow variants valid (as they miss a definition)
Also:
- there were some linting issues failing the master as well
- some autformatting via `gofumpt` and `goimports` (let me know if they're not welcome 😅 )
[CI-4035]: https://bitrise.atlassian.net/browse/CI-4035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

Understand workflow variants when validating the pipeline [CI-4035]

---

version/build.go

The next version will be: 2.25.1
This PR bumps the Bitrise CLI version to 2.25.1, to release:
- [Step bundle validation](https://github.com/bitrise-io/bitrise/pull/1034)

Bump version number

---

version/build.go

The next version will be 2.25.2
This PR bumps the CLI version to 2.25.2 to release:
- https://github.com/bitrise-io/bitrise/pull/1033
- https://github.com/bitrise-io/bitrise/pull/1034
- https://github.com/bitrise-io/bitrise/pull/1036

Bump version to 2.25.2

---

_tests/integration/helper.go
_tests/integration/json_params_test.go
_tests/integration/modular_config_main.yml
_tests/integration/modular_config_test.go
_tests/integration/new_trigger_test.go
_tests/integration/validate_test.go
configmerge/config_reader.go
configmerge/configmerge_test.go
configmerge/git_url.go
configmerge/git_url_test.go
configmerge/reference.go

This PR fixes an issue where the Bitrise CLI and the bitrise.io Backend use different formats for the `include.repository` property in the bitrise.yml file.
The Bitrise CLI expects the module's repository URL (`https://github.com/bitrise-io/bitrise.git`), while the Backend supports remote config modules from the same git org only and works with the config module's repository name (`bitrise`).
With this change, Bitrise CLI switches to the repository name format. This is just a format change because under the hood we will still `git clone` remote config modules, the full module repository path is derived from the current project's repository URL.

Fix include.repository format

---

_tests/integration/step_bundles_test.go
_tests/integration/step_bundles_test_bitrise.yml
cli/run.go
cli/run_test.go
cli/run_util.go
models/models.go
models/models_methods.go
models/models_methods_test.go

This PR introduces `inputs` for Step Bundles.
Currently, Step Bundles can be configured with `envs`. The new `inputs` are meant to replace `envs` in the future to unify how different entities in bitrise.yml can be configured.
Step Bundle related analytics are under an update to contain information about the actual usage of Step Bundle `envs`, based on the data we either just remove `envs` from bitrise.yml or deprecate it in a later PR. For now `inputs` and `envs` live next to each other, but `inputs` have priority over `envs` (a Step Bundle input overrides a Step Bundle env with the same key).
The only difference between inputs and envs is that inputs need to be defined on the step bundle, to be able to step value when used in a …

Step bundle inputs

---

models/models.go
version/build.go

The next version will be: 2.27.0
This PR bumps the CLi version to 2.27.0 and the bitrise.yml format version to 19, to release:
- https://github.com/bitrise-io/bitrise/pull/1045

Bump CLI version and bitrise.yml format version

---

configmerge/config_reader.go
configmerge/configmerge.go
configmerge/configmerge_test.go
configmerge/debug_logger.go

This PR adds debug logs for the config merge process to support debugging.
The new debug logs look like this:
```
[DEBUG] POST https://step-analytics.bitrise.io/track
[14:48:31] Merge config modules included in bitrise.yml
[14:48:31] reading local config module at: bitrise.yml
[14:48:31] Building config tree
[14:48:31] reading local config module at: ./../config-module/module.yml
[14:48:31] reading remote config module 'module.yml' from repo 'sample-artifacts' on commit '86f6dc5eec51cfcd2e70c0dff19e4ca466e353e5'
[14:48:31] getting current repository url
[14:48:31] current repository url: git@github.com:bitrise-io/config-main.git
[14:48:31] cloning repository 'git@github.com:bitrise-io/sample-artifacts.git' with commit …
```

Add debug logs for the config merge process

---

configs/agent_config.go
configs/agent_config_test.go

In agent config mode the HTML_REPORT_DIR was not usable, as it was not expanded and created on init. Fixed this oversight.

Expand and create HTML_REPORT_DIR in agent config mode.

---

version/build.go

The next release version will be: 2.30.0
This PR bumps the CLI version from 2.29.4 to 2.30.0, to release:
- https://github.com/bitrise-io/bitrise/pull/1063

Bump CLI version to 2.30.0

---

bitrise/dependencies.go
bitrise/setup.go
go.mod
go.sum
tools/tools.go
vendor/github.com/bitrise-io/envman/v2/cli/add.go
vendor/github.com/bitrise-io/envman/v2/version/version.go
vendor/modules.txt

This change will be released under version 2.30.2
This PR updates the CLI's min envman version. The [new envman version](https://github.com/bitrise-io/envman/releases/tag/v2.5.3) improves error messages related to the env var size limits.

Update envman dep and envman tool min version to 2.5.3

---

bitrise.yml
go.mod
tools/tools.go
tools/tools_test.go
version/build.go

The new version will be 2.30.4
This PR fixes envman and stepman tool version comparison at tool download URL creation. Also updates the HTTP client's logger to print logs as debug logs, to make `bitrise setup` less noisy.

Fix tool version compare

---

bitrise/util.go
bitrise/util_test.go
tools/env.go
tools/env_test.go
version/build.go

This PR limits the BITRISE_FAILED_STEP_ERROR_MESSAGE env var value to 1KB, because Steps might produce a large error message, which can exceed the env var value and env var list limits.

Limit failed step env vars size

---

.goreleaser.yaml
_tests/integration/docker_test.go

In version 2.29.2 the project's package was updated to `github.com/bitrise-io/bitrise/v2`, but in the `.goreleaser.yaml` config, the version package's name was not updated. Because of this, no proper version information was built into the binaries, e.g.:
```
$ bitrise version --full
version: 2.30.5
format version: 23
os: darwin (arm64)
go: go1.22.7
build number: 
commit: (devel)
```
This PR fixes the issue by updating the version package name in `.goreleaser.yaml`.

Update version package name

---

version/build.go

This PR bumps the CLI version to 2.30.6 to release:
- https://github.com/bitrise-io/bitrise/pull/1076
- https://github.com/bitrise-io/bitrise/pull/1079

Bump version number to 2.30.6

---

_tests/integration/workflow_run_envs_test.go
_tests/integration/workflow_run_envs_test_bitrise.yml
bitrise.yml
cli/run_util.go

`BITRISE_BUILD_STATUS` env was not set to failing inside a Step bundle.
```
workflows:
debug:
steps:
- bundle::failing_step_bundle: { }
step_bundles:
failing_step_bundle:
title: Failing step
steps:
- script@1:
title: Failing step
inputs:
- content: |-
#!/usr/bin/env bash
set -ex
exit 1
- script@1:
title: Build status NOT failing
is_always_run: true
inputs:
- content: |-
#!/usr/bin/env bash
set -ex
echo "$BITRISE_BUILD_STATUS"
```

Fixing Build status for step bundles

---

version/build.go

This PR bumps Bitrise CLI version to 2.32.1 to release a [fix for Step Bundle run_if property](https://github.com/bitrise-io/bitrise/pull/1100).

Bump CLI version

---

_tests/integration/toolprovider/asdf/install_error_test.go
_tests/integration/toolprovider/mise/install_error_test.go
_tests/integration/toolprovider/mise/install_flutter_test.go
_tests/integration/toolprovider/mise/install_golang_test.go
_tests/integration/toolprovider/mise/install_java_test.go
_tests/integration/toolprovider/mise/install_nodejs_test.go
_tests/integration/toolprovider_test.go
_tests/integration/toolprovider_test_mise_bitrise.yml
_tests/integration/validate_test.go
toolprovider/asdf/asdf.go
toolprovider/asdf/install.go
toolprovider/asdf/install_plugin.go
toolprovider/mise/bootstrap.go
toolprovider/mise/env.go
toolprovider/mise/env_test.go
toolprovider/mise/execenv/execenv.go
toolprovider/mise/install.go
toolprovider/mise/install_test.go
toolprovider/mise/mise.go
toolprovider/mise/resolve.go
toolprovider/provider/provider.go
toolprovider/run.go

#1106 
Can be reviewed commit by commit. First commit is copy-paste from the toolprovider repo without any changes (other than imports). The rest are additional small changes on top of the original impl.

Toolprovider: Mise
