bitrise-io/bitrise

bitrise.yml
bitrise/run.go
bitrise/util.go
cli/cli.go
cli/doSetup.go

envman can now be auto-installed with setup

setup and other minor changes

---

bitrise/dependencies.go
bitrise/setup.go

but brew check is extended with brew update and brew doctor

Xcode CLT is not an explicit dependency anymore, only brew

---

bitrise.yml
bitrise/paths.go
cli/doRun.go

so far only one: BITRISE_STEP_FORMATTED_OUTPUT_FILE_PATH

set predefined ENVs

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/bitrise-io/go-utils/stringutil/stringutil.go
Godeps/_workspace/src/github.com/bitrise-io/go-utils/stringutil/stringutil_test.go
bitrise/print.go
cli/run_util.go

Mainly affects the steps which are not used from a steplib

step log version printing fix - trimming version string.

---

bitrise/util_test.go
tools/tools_test.go

fix in tests, to make `go test ./...` work after a clean checkout

---

bitrise/dependencies.go
cli/run_util.go

related issue: https://github.com/bitrise-io/bitrise/issues/416

just a minor dep install text change/clarification

---

toolkits/golang.go

bumped Go version for toolkit to 1.7.3

---

bitrise/dependencies.go

fixing https://github.com/bitrise-io/bitrise/issues/433

apt get package installed check fix

---

bitrise.yml
bitrise/setup.go
plugins/git.go

envman min version bumped to: 1.1.2
analytics min version bumped to: 0.9.6
bitrise.yml update

deps updates

---

bitrise.yml
models/models_methods.go
models/models_methods_test.go

- triggers -> validate whether workflow exists
- triggers -> validate whether duplicate patterns with same type

Bitrise yml validation

---

bitrise.yml
bitrise/print.go
bitrise/setup.go

- create-release wf update
- switch workflow log fix
- min stepman version bumped to 0.9.28
- workflow-editor default plugin

Prepare for new version

---

cli/export.go

`bitrise export` should display the help - completed

Bitrise export fix

---

_tests/integration/log_filter_disabled_test_secrets.yml
cli/run.go
cli/trigger.go
tools/tools.go

- secret filtering flab moved to const
- removed filtering warning from step logs
- do not hide secret filtering env

secret filtering update

---

_docs/step-development-guideline.md

Clarify step dependencies.
For first this PR should be technically correct, later i will ask the devcenter team to pimp the text.

step dependencies clarification

---

_docs/bitrise-yml-format-spec.md
_docs/step-development-guideline.md
models/models.go
models/models_methods.go

The following PRs should be checked:
https://github.com/bitrise-io/bitrise-init/pull/164
https://github.com/bitrise-io/bitrise-add-new-project/pull/30
https://github.com/bitrise-io/bitrise/pull/673 (This)

TOOL-134 Added stack as meta data to app model.

---

cli/run_util.go

Do not know why "./" was resolved to "/" in the report. Moved copying step.yml earlier so we can fail before copying anything else.

Try to copy step.yml first

---

bitrise/setup.go

updated workflow editor plugin version to 1.1.67

prepare release 1.37.0

---

cli/run_util.go

Move StepLib step activation logic to a separate function: `activateStepLibStep`

Tool 387 version lock

---

tools/tools.go

- small refactoring
- logging enhancement: log warning if error during secret key-value extraction

Tool 838 dont ignore err in envmanrun

---

Gopkg.lock
Gopkg.toml
vendor/github.com/bitrise-io/stepman/version/version.go
vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go

from github.com/Sirupsen/logrus to github.com/sirupsen/logrus

Update logrus dependency 

---

plugins/model_methods_test.go
plugins/models_methods.go
plugins/paths.go

Support installing plugin with `triggers` filed specified in the `plugin.yml`.
Resolves: [STEP-627](https://bitrise.atlassian.net/browse/STEP-627)

Support installing plugin with triggers

---

_tests/integration/timeout_no_output.yml
_tests/integration/timeout_no_output_test.go
_tests/integration/version_test.go
cli/run_util.go
go.mod
go.sum
models/models.go
models/models_methods.go
plugins/run.go
tools/tools.go
vendor/github.com/bitrise-io/stepman/cli/cli.go
vendor/github.com/bitrise-io/stepman/cli/version.go
vendor/github.com/bitrise-io/stepman/models/models.go
vendor/github.com/bitrise-io/stepman/models/models_methods.go
vendor/github.com/bitrise-io/stepman/version/build.go
vendor/github.com/bitrise-io/stepman/version/version.go
vendor/modules.txt

Add support for Step property `no_output_timeout`.
Resolves: https://bitrise.atlassian.net/browse/BE-170

Add support for new property

---

bitrise/setup.go
version/build.go

Update tools and plugins

---

bitrise/setup.go

Update the cli to use the latest tool versions.

Update tool versions

---

analytics/legacy.go

Fix typo in legacy.go

---

analytics/legacy.go

chore: TIP-997 change analyticsServerURL

---

version/build.go

Mandatory version bump update before releasing a fix:
- https://github.com/bitrise-io/bitrise/pull/851
- Bump version number to 2.2.3

Bump version to 2.2.3

---

models/models_methods.go
models/models_methods_test.go

fix: disallow utility workflows in pipeline stage [SWAT-1418] [CI-762]

---

version/build.go

New version number for the next release.
Update version number to 2.2.4.

Update version number

---

version/build.go

This PR bumps Bitrise CLI version from 2.2.4 to 2.2.5 for releasing:
- https://github.com/bitrise-io/bitrise/pull/856
- https://github.com/bitrise-io/bitrise/pull/858
- https://github.com/bitrise-io/bitrise/pull/859
- https://github.com/bitrise-io/bitrise/pull/862
- Version number update

Update version number to 2.2.5

---

configs/paths.go
go.mod
go.sum
plugins/git.go
plugins/install.go
plugins/install_test.go
toolkits/swift.go
vendor/github.com/bitrise-io/go-utils/pathutil/pathutil.go
vendor/modules.txt

\[[CI-763](https://bitrise.atlassian.net/browse/CI-763)\] The bitrise plugin executables have `777` permissions inside the `~/.bitrise` folder. This is a security risk and we should use `755` instead.
Also the whole `~/.bitrise` folder has `777` permission which seems like too forgiving. We could potentially change the root and all of the subfolders to `755`.
* Make the following files/directories with `755` file permission instead of `777`:
* Bitrise temp work directory
* Bitrise temp Steps directory inside work directory
* The directory plugins are cloned into
* Plugin bin/src/data temp directories
* Plugin bin/src/data directories
* Plugin binary itself
* Swift binary directory
* Related PR: …

Use 755 file permission instead of 777 for plugin binaries

---

models/models.go

\[[CI-1365](https://bitrise.atlassian.net/browse/CI-1365)\] The `validate` subcommand does not validate the `should_always_run` and `abort_on_fail` fields.
* Added the missing properties to the stage model
In fact, the cli is missing these properties. That's why they're not being validated.
Before:
After:
[CI-1365]: https://bitrise.atlassian.net/browse/CI-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added missing properties to stage model

---

bitrise/setup.go
version/build.go

Updating the workflow-editor and CLI version numbers before the release.

Update version numbers

---

_tests/integration/new_trigger_test.go
cli/commands.go
cli/run_trigger_params.go
cli/run_trigger_params_test.go
cli/trigger.go
cli/trigger_check.go
models/trigger_map.go
models/trigger_map_item.go
models/trigger_map_item_test.go

update draft pr trigger check param

---

version/build.go

v2.12.0 was released without bumping the version number string, let's make sure the next version is released correctly

Prepare next version

---

_tests/integration/docker_create_bitrise.yml
_tests/integration/docker_pull_bitrise.yml
_tests/integration/docker_service_bitrise.yml
_tests/integration/docker_start_fails_bitrise.yml
_tests/integration/docker_test.go
cli/run.go
cli/run_util.go
models/models.go
models/models_methods.go
models/models_methods_test.go

Containerization-related configuration is getting refactored:
1, Moving service and container configuration to new top-level entities (`services` and `containers`)
From this:
```
workflows:
primary:
container:
image: ruby:3.2
services:
postgres:
image: postgres:13
```
to this:
```
services:
postgres:
image: postgres:13
containers:
ruby:
image: ruby:3.2
workflows:
primary:
container: ruby
services:
- postgres
```
2, Step grouping mechanism with a new step list item (`with`)
From this:
```
workflows:
_setup:
steps:
- activate-ssh-key: { }
- git-clone: {}
test:
before_run:
- _setup
container: ruby
services:
- postgres
steps:
- script:
title: Setup DB
inputs:
- content: bundle exec rails db:setup
- script:
title: Run tests …
```

Refactor containerisation 1

---

version/build.go

Just the usual version bump before the release.

Release version bump

---

_tests/integration/offline_mode.yml
_tests/integration/offline_mode_test.go
bitrise/setup.go
cli/cli.go
cli/commands.go
cli/preload_steps.go
cli/run.go
cli/run_util.go
cli/run_util_test.go
cli/setup.go
cli/step_activator.go
configs/configs.go
go.mod
go.sum
log/log.go
models/workflow_run_plan.go
tools/tools.go
vendor/github.com/bitrise-io/stepman/cli/activate.go
vendor/github.com/bitrise-io/stepman/cli/errors.go
vendor/github.com/bitrise-io/stepman/cli/step_list.go
vendor/github.com/bitrise-io/stepman/models/version_constraint.go
vendor/github.com/bitrise-io/stepman/preload/preload_steps.go
vendor/github.com/bitrise-io/stepman/preload/preload_steps_util.go
vendor/github.com/bitrise-io/stepman/stepman/library.go
vendor/modules.txt

Added *steps* command with subcommands:
```
list-cached     List all the cached steps
preload         Makes sure that Bitrise CLI can be used in offline mode by preloading Bitrise maintaned Steps.
```
The preload can be configured like this:
```
NAME:
bitrise steps preload - Makes sure that Bitrise CLI can be used in offline mode by preloading Bitrise maintaned Steps.
USAGE:
Use the BITRISE_OFFLINE_MODE env var to test after preloading steps.
OPTIONS:
--steplib-url value    URL of the steplib to list or preload steps from (default: "https://github.com/bitrise-io/bitrise-steplib.git")
--maintainer value     Maintainer of the steps to list or preload (default: "bitrise")
--majors value         Include X latest major versions (default: …
```

Add offline support

---

go.mod
go.sum
vendor/github.com/bitrise-io/stepman/toolkits/golang_min_version.go
vendor/modules.txt

Updated minimum Golang version used for steps to 1.20.

[ACI-2272] Updated min go version of steps to 1.20

---

_tests/integration/docker_create_bitrise.yml
_tests/integration/docker_multiple_containers_bitrise.yml
_tests/integration/docker_multiple_containers_secrets.yml
_tests/integration/docker_pull_bitrise.yml
_tests/integration/docker_service_bitrise.yml
_tests/integration/docker_start_fails_bitrise.yml
_tests/integration/docker_test.Dockerfile.healthy-container
_tests/integration/docker_test.go
cli/docker/container_manager.go
cli/run.go
cli/run_util.go
models/models.go
models/models_methods.go
models/models_methods_test.go
models/workflow_run_plan.go

This PR proposes the previously introduced containerization configuration-related changes to `master`:
- https://github.com/bitrise-io/bitrise/pull/952
- https://github.com/bitrise-io/bitrise/pull/956

Refactor containerisation

---

models/models.go
version/build.go

This PR adds omitempty to the newly introduced `services` and `containers` top-level config entities.
<!-- 
Details are important, and help maintainers processing your PR.
Please list additional details, for example:
- Update dependencies
- Make `foo` optional in `main.go`
- `foo` now returns an `error` for better error handling
--

Models update

---

version/build.go

Just the usual version bump before release.

Bump version

---

version/build.go

This PR updates the tool version to 2.19.0 to release:
- https://github.com/bitrise-io/bitrise/pull/982 and
- https://github.com/bitrise-io/bitrise/pull/987

Bump version to 2.19.0

---

go.mod
go.sum
vendor/github.com/bitrise-io/stepman/activator/steplib_ref.go
vendor/modules.txt

This PR pulls a step activation-related bugfix for the stepman/activator package: https://github.com/bitrise-io/stepman/pull/335

Pull stepman with steplib update fix

---

version/build.go

This PR updates Bitrise CLI version number to 2.21.0 for releasing:
- https://github.com/bitrise-io/bitrise/pull/997
- https://github.com/bitrise-io/bitrise/pull/1000
- https://github.com/bitrise-io/bitrise/pull/999
- https://github.com/bitrise-io/bitrise/pull/1001

Bump version to 2.21.0

---

.goreleaser.yaml
bitrise.yml

[SVC-3123] feat: upload binaries to an other Object Storage as well

---

.goreleaser.yaml

[SVC-0] fix: goreleaser bucket region

---

.goreleaser.yaml

[SVC-0] fix: goreleaser s3 endpoint

---

version/build.go

This PR bumps version to 2.24.1 to release:
- https://github.com/bitrise-io/bitrise/pull/1015

Bump version to 2.24.1

---

models/models.go

This PR will reenable the run_if graph pipeline support.

[CI-3776] Reenable run_if

---

version/build.go

Usual version bump before the release.

Bump version to 2.24.2

---

cli/run_util_pipeline_test.go
models/models_methods.go

The pipeline validation loop was only validation the first pipeline in the list.

Fix pipeline validation loop

---

.goreleaser.yaml
bitrise.yml

This PR updates the goreleaser config to comply with the latest v2 goreleaser.

Update goreleaser config

---

models/models.go
models/models_methods.go
models/models_methods_test.go

The workflow variant input validation was missing from the CLI.

[CI-3991] Add input validation

---

version/build.go

Regular version bump before release.

Update to 2.26.0

---

bitrise.yml

This PR updates the `create-release` workflow's version check step, to get the current version with `go run main.go --version --version`.

Get current version using go run

---

models/models.go
version/build.go

This PR adds `title`, `summary`, and `description` fields to the Step bundle data models, to uniform it with other bitrise.yml entities.
Also, the format version and CLI version are bumped to prepare for releasing the changes.

Step bundle title summary description

---

bitrise.yml
version/build.go

Fix version-tag comparison and bump version

---

go.mod
go.sum
vendor/github.com/bitrise-io/stepman/toolkits/golang_min_version.go
vendor/github.com/bitrise-io/stepman/version/version.go
vendor/modules.txt
version/build.go

Update minumum golang version

---

version/build.go

The next version will be 2.30.3
This PR updates the CLI version to 2.30.3 to release:
- https://github.com/bitrise-io/bitrise/pull/1073

Update CLI version

---

plugins/run.go

Use os.Stdout and os.Stderr for streams of plugins

---

models/models.go
models/selective_triggers.go
models/selective_triggers_test.go
version/build.go

Add `last_commit` option to `changed_files` and `commit_messages` trigger filters for push events.

[BIVS-3126] Last commit option for push trigger filters

---

bitrise.yml

Updated the CI configuration to install golangci-lint using the official binary installation script directly in the workflow, removing any dependency on external repositories or custom install directories.

WF change: go linter

---

_tests/integration/step_bundle_run_if_test.go
_tests/integration/step_bundle_run_if_test_bitrise.yml
cli/run_test.go
cli/run_util.go
models/models.go
models/workflow_run_plan.go
models/workflow_run_plan_test.go

This PR introduces a `run_if` property on Step Bundles.
The `run_if` condition controls the execution of the Steps (and Step Bundles) within the given Step Bundle, if the condition is evaluated to false, all Steps (and Step Bundles) are skipped.

Step bundle run if

---

toolprovider/asdf/activate.go
toolprovider/asdf/asdf.go
toolprovider/asdf/parse.go

Toolprovider: resolve some TODOs

---

bitrise/setup.go
toolprovider/asdf/asdf.go
toolprovider/log.go
toolprovider/log_test.go
toolprovider/run.go

Nicer toolprovider logs

---

version/build.go

Bump version to 2.33.0

---

toolprovider/log.go
toolprovider/log_test.go
toolprovider/run.go

Measure tool setup time

---

_tests/integration/toolprovider/mise/install_backend_test.go

Add tests for alternative Mise backends

---

version/build.go

Version bump: 2.34.1

---

integrationtests/toolprovider/asdf/execenv_test.go
integrationtests/toolprovider/mise/execenv_test.go
toolprovider/asdf/execenv/execenv.go
toolprovider/mise/env.go
toolprovider/mise/execenv/execenv.go
toolprovider/mise/install.go
toolprovider/mise/resolve.go

Use timeout for tool setup commands
